-- DROP TABLE IF EXISTS urls;
-- DROP TABLE IF EXISTS url_checks;

CREATE TABLE if NOT EXISTS urls (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
);

CREATE TABLE if NOT EXISTS url_checks (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    id_url BIGINT REFERENCES urls(id) NOT NULL
    status_code int NOT NULL,
    h1 VARCHAR(50),
    title VARCHAR(150),
    description VARCHAR(255),
    created_at TIMESTAMP,
);