name: test

on:
    push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make build
      - name: Run linter
        run: |
          make linter
      - uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: qltcp_0f1E6qK0kIebjjXP
          files: target/lcov.info
